In [1]:
import numpy as np
from numpy import *
import scipy.linalg as slin

In [2]:
#declaring the array
a = np.zeros((28,28))
#print("Matrix A=",a)
#print(type(a))
b = np.zeros((28,1))
#print("Matrix B=",b)
#print(type(b))
for x in range(28):
    if((x%4)==0):
        b[x]=-5
    elif((x%4)==3):
        b[x]=+5
#print("Matrix B=",b)
#print(len(a))
#print(len(a[0]))
up = 4
for x in range(len(a)):
    for y in range(len(a[0])):
        if(y==x):
            a[x][y]=-4
        elif((y==(x+1)) and ((y%4)!=0)):
            a[x][y]=1
        elif((x==(y+1)) and ((x%4)!=0)):
            a[x][y]=1
for x in range(len(a)):
    for y in range(len(a[0])):
        if((y==(x+up)) or (x==(y+up))):
            a[x][y]=1
#print(a)
#print(b)

In [3]:
print("Determinant of a=",slin.det(a))  #Determinant of the array
print("Trace of a=",np.trace(a))        #Trace of the array
#print("Transpose=",np.transpose(a))#Transpose of the array
#print("Inverse=",slin.inv(a))      #Inverse of the array

Determinant of a= 1342421467113968.2
Trace of a= -112.0


In [4]:
#horizontal_distance and vertical_distance between grid 
hor_d = 0.162/5
ver_r = 6/8

#80 elements and 6 for P1,P2,P3,Q1,Q2,Q3
element_parameter = np.zeros((80,6))
for x in range(len(element_parameter)):
    if((x%2)==0):
        element_parameter[x][0]=0
        element_parameter[x][1]=ver_r
        element_parameter[x][2]=-ver_r
        element_parameter[x][3]=-hor_d
        element_parameter[x][4]=0
        element_parameter[x][5]=hor_d
    elif((x%2)!=0):
        element_parameter[x][0]=-ver_r
        element_parameter[x][1]=ver_r
        element_parameter[x][2]=0
        element_parameter[x][3]=0
        element_parameter[x][4]=-hor_d
        element_parameter[x][5]=hor_d
print(" ")
print("    P1      P2      P3      Q1      Q2      Q3")
print(element_parameter)

#Element Coefficient Matrix of Each Element
coeff = [None]*80
for x in range(len(coeff)):
    coeff[x] = np.zeros((3,3))
for x in range(len(coeff)):
    for y in range(len(coeff[x])):
        for z in range(len((coeff[x])[0])):
            (coeff[x])[y][z]=(((element_parameter[x][y]*element_parameter[x][z])+(element_parameter[x][y+3]*element_parameter[x][z+3]))/((element_parameter[x][1]*element_parameter[x][5])-(element_parameter[x][2]*element_parameter[x][4])))
print(" ")
print("Element Coefficient Matrix Of All Elements:")
print(" ")
print(coeff)

#Overall/Global Coefficient Matrix
#print("Overall/Global Coefficient Matrix:")
#overall = np.zeros((54,54))
#print(overall)

 
    P1      P2      P3      Q1      Q2      Q3
[[ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324  0.      0.0324]
 [-0.75    0.75    0.      0.     -0.0324  0.0324]
 [ 0.      0.75   -0.75   -0.0324

In [5]:
#print((slin.inv(a)).dot(b))
#print("Length=",len((slin.inv(a)).dot(b)))
c = (slin.inv(a)).dot(b)
for x in range(len(c)):
    print("Calculated Voltage at Free Node ",x+1,"equals ",c[x])

Calculated Voltage at Free Node  1 equals  [2.07168166]
Calculated Voltage at Free Node  2 equals  [0.58345078]
Calculated Voltage at Free Node  3 equals  [-0.58345078]
Calculated Voltage at Free Node  4 equals  [-2.07168166]
Calculated Voltage at Free Node  5 equals  [2.70327586]
Calculated Voltage at Free Node  6 equals  [0.84557225]
Calculated Voltage at Free Node  7 equals  [-0.84557225]
Calculated Voltage at Free Node  8 equals  [-2.70327586]
Calculated Voltage at Free Node  9 equals  [2.89584952]
Calculated Voltage at Free Node  10 equals  [0.94113463]
Calculated Voltage at Free Node  11 equals  [-0.94113463]
Calculated Voltage at Free Node  12 equals  [-2.89584952]
Calculated Voltage at Free Node  13 equals  [2.93898761]
Calculated Voltage at Free Node  14 equals  [0.96425137]
Calculated Voltage at Free Node  15 equals  [-0.96425137]
Calculated Voltage at Free Node  16 equals  [-2.93898761]
Calculated Voltage at Free Node  17 equals  [2.89584952]
Calculated Voltage at Free Node 

In [6]:
volt = np.zeros((7,4))
for x in range(len(c)):
    volt[(int)(x/4)][(x%4)]=c[x]
pos_volt = 5*(np.ones((7,1)))
neg_volt = -5*(np.ones((7,1)))
#print(pos_volt,neg_volt)
#print(volt)
new_volt = np.hstack((pos_volt,volt,neg_volt))
print("Voltages at different nodes in solution region:")
print(" ")
print(new_volt)
print(" ")
d = 0.162/500
ele = np.zeros((7,5))
#print(ele)
for x in range(len(ele)):
    for y in range(len(ele[0])):
        ele[x][y] = (new_volt[x][y]-new_volt[x][y+1])/d
print("Electric Field at different region in solution region:")
print(" ")
print(ele)

Voltages at different nodes in solution region:
 
[[ 5.          2.07168166  0.58345078 -0.58345078 -2.07168166 -5.        ]
 [ 5.          2.70327586  0.84557225 -0.84557225 -2.70327586 -5.        ]
 [ 5.          2.89584952  0.94113463 -0.94113463 -2.89584952 -5.        ]
 [ 5.          2.93898761  0.96425137 -0.96425137 -2.93898761 -5.        ]
 [ 5.          2.89584952  0.94113463 -0.94113463 -2.89584952 -5.        ]
 [ 5.          2.70327586  0.84557225 -0.84557225 -2.70327586 -5.        ]
 [ 5.          2.07168166  0.58345078 -0.58345078 -2.07168166 -5.        ]]
 
Electric Field at different region in solution region:
 
[[9038.01956569 4593.30517792 3601.54804365 4593.30517792 9038.01956569]
 [7088.65475371 5733.65310234 5219.58181876 5733.65310234 7088.65475371]
 [6494.2915931  6033.07065897 5809.47302673 6033.07065897 6494.2915931 ]
 [6361.14936663 6094.86491369 5952.16897021 6094.86491369 6361.14936663]
 [6494.2915931  6033.07065897 5809.47302673 6033.07065897 6494.2915931 ]


In [7]:
epsilon=8.854187871*10**-12
flux_density = 5*epsilon*ele
print("Flux Density:")
print(" ")
print(flux_density)
ref = np.ones((5,1))
net_flux_density = flux_density.dot(ref)
print(" ")
print("Net Flux Density in one direction:")
print(" ")
print(net_flux_density)

Flux Density:
 
[[4.00121616e-07 2.03349935e-07 1.59443915e-07 2.03349935e-07
  4.00121616e-07]
 [3.13821405e-07 2.53834209e-07 2.31075790e-07 2.53834209e-07
  3.13821405e-07]
 [2.87508389e-07 2.67089705e-07 2.57190828e-07 2.67089705e-07
  2.87508389e-07]
 [2.81614058e-07 2.69825395e-07 2.63508112e-07 2.69825395e-07
  2.81614058e-07]
 [2.87508389e-07 2.67089705e-07 2.57190828e-07 2.67089705e-07
  2.87508389e-07]
 [3.13821405e-07 2.53834209e-07 2.31075790e-07 2.53834209e-07
  3.13821405e-07]
 [4.00121616e-07 2.03349935e-07 1.59443915e-07 2.03349935e-07
  4.00121616e-07]]
 
Net Flux Density in one direction:
 
[[1.36638702e-06]
 [1.36638702e-06]
 [1.36638702e-06]
 [1.36638702e-06]
 [1.36638702e-06]
 [1.36638702e-06]
 [1.36638702e-06]]


In [8]:
length_of_plate = 0.06
width_of_plate = 0.01
Area_of_plate = length_of_plate*width_of_plate
Total_flux = net_flux_density[0][0]*Area_of_plate
print("Total Flux through Epoxy dielectic:",Total_flux)

Total Flux through Epoxy dielectic: 8.198322102777779e-10


In [9]:
#From Gauss Law net flux passing through an area is equal to the charge enclosed within the gaussian surface
charge = Total_flux
Capacitance = charge/5
print("Capacitance is equal to =",Capacitance)

Capacitance is equal to = 1.6396644205555557e-10
