In [1]:
import numpy as np
from numpy import *
import scipy.linalg as slin

In [2]:
hor_d = 0.162/3
ver_r = 6/6

In [3]:
#36 elements and 6 for P1,P2,P3,Q1,Q2,Q3
element_parameter = np.zeros((36,6))
for x in range(len(element_parameter)):
    if((x%2)==0):
        element_parameter[x][0]=-ver_r
        element_parameter[x][1]=0
        element_parameter[x][2]=ver_r
        element_parameter[x][3]=hor_d
        element_parameter[x][4]=-hor_d
        element_parameter[x][5]=0
    elif((x%2)!=0):
        element_parameter[x][0]=-ver_r
        element_parameter[x][1]=ver_r
        element_parameter[x][2]=0
        element_parameter[x][3]=0
        element_parameter[x][4]=-hor_d
        element_parameter[x][5]=hor_d
print(" ")
print(" P1      P2      P3      Q1      Q2    Q3")
print(element_parameter)

 
 P1      P2      P3      Q1      Q2    Q3
[[-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1.     0.     0.    -0.054  0.054]
 [-1.     0.     1.     0.054 -0.054  0.   ]
 [-1.     1

In [4]:
coeff = [None]*36
for x in range(len(coeff)):
    coeff[x] = np.zeros((3,3))
for x in range(len(coeff)):
    for y in range(len(coeff[x])):
        for z in range(len((coeff[x])[0])):
            (coeff[x])[y][z]=(((element_parameter[x][y]*element_parameter[x][z])+(element_parameter[x][y+3]*element_parameter[x][z+3]))/(2*((element_parameter[x][1]*element_parameter[x][5])-(element_parameter[x][2]*element_parameter[x][4]))))
print(" ")
print("Element Coefficient Matrix Of All Elements:")
print(" ")
print(coeff)

 
Element Coefficient Matrix Of All Elements:
 
[array([[ 9.28625926, -0.027     , -9.25925926],
       [-0.027     ,  0.027     ,  0.        ],
       [-9.25925926,  0.        ,  9.25925926]]), array([[ 9.25925926, -9.25925926,  0.        ],
       [-9.25925926,  9.28625926, -0.027     ],
       [ 0.        , -0.027     ,  0.027     ]]), array([[ 9.28625926, -0.027     , -9.25925926],
       [-0.027     ,  0.027     ,  0.        ],
       [-9.25925926,  0.        ,  9.25925926]]), array([[ 9.25925926, -9.25925926,  0.        ],
       [-9.25925926,  9.28625926, -0.027     ],
       [ 0.        , -0.027     ,  0.027     ]]), array([[ 9.28625926, -0.027     , -9.25925926],
       [-0.027     ,  0.027     ,  0.        ],
       [-9.25925926,  0.        ,  9.25925926]]), array([[ 9.25925926, -9.25925926,  0.        ],
       [-9.25925926,  9.28625926, -0.027     ],
       [ 0.        , -0.027     ,  0.027     ]]), array([[ 9.28625926, -0.027     , -9.25925926],
       [-0.027     ,  0.027

In [5]:
print("Overall/Global Coefficient Matrix:")
overall = np.zeros((28,28))
overall[0][0]=(coeff[0])[0][0]
overall[1][0]=(coeff[0])[0][2]
overall[1][1]=(coeff[0])[2][2]+(coeff[1])[2][2]+(coeff[2])[0][0]
overall[2][0]=0
overall[2][1]=(coeff[2])[2][0]
overall[2][2]=(coeff[2])[2][2]+(coeff[3])[2][2]+(coeff[4])[0][0]
overall[3][0]=0
overall[3][1]=0
overall[3][2]=(coeff[4])[0][2]
overall[3][3]=(coeff[4])[2][2]+(coeff[5])[2][2]
overall[4][0]=(coeff[0])[0][1]
overall[4][1]=(coeff[0])[1][2]+(coeff[1])[2][0]
overall[4][2]=0
overall[4][3]=0
overall[4][4]=(coeff[0])[1][1]+(coeff[1])[0][0]+(coeff[6])[0][0]
overall[5][0]=0
overall[5][1]=(coeff[1])[1][2]+(coeff[2])[1][0]
overall[5][2]=(coeff[2])[1][2]+(coeff[3])[0][2]
overall[5][3]=0
overall[5][4]=(coeff[1])[0][1]+(coeff[6])[0][2]
overall[5][5]=(coeff[1])[1][1]+(coeff[2])[1][1]+(coeff[3])[0][0]+(coeff[8])[0][0]+(coeff[7])[2][2]+(coeff[6])[2][2]
overall[6][0]=0
overall[6][1]=0
overall[6][2]=(coeff[3])[1][2]+(coeff[4])[0][1]
overall[6][3]=(coeff[4])[1][2]+(coeff[5])[0][2]
overall[6][4]=0
overall[6][5]=(coeff[3])[0][1]+(coeff[8])[0][2]
overall[6][6]=(coeff[4])[1][1]+(coeff[5])[0][0]+(coeff[10])[0][0]+(coeff[9])[2][2]+(coeff[8])[2][2]+(coeff[3])[1][1]
overall[7][0]=0
overall[7][1]=0
overall[7][2]=0
overall[7][3]=(coeff[5])[1][2]
overall[7][4]=0
overall[7][5]=0
overall[7][6]=(coeff[5])[0][1]+(coeff[10])[0][2]
overall[7][7]=(coeff[5])[1][1]+(coeff[10])[2][2]+(coeff[11])[2][2]
overall[8][0]=0
overall[8][1]=0
overall[8][2]=0
overall[8][3]=0
overall[8][4]=(coeff[6])[1][0]
overall[8][5]=(coeff[6])[1][2]+(coeff[7])[0][2]
overall[8][6]=0
overall[8][7]=0
overall[8][8]=(coeff[6])[1][1]+(coeff[7])[0][0]+(coeff[12])[0][0]
overall[9][0]=0
overall[9][1]=0
overall[9][2]=0
overall[9][3]=0
overall[9][4]=0
overall[9][5]=(coeff[7])[1][2]+(coeff[8])[1][0]
overall[9][6]=(coeff[8])[1][2]+(coeff[9])[0][2]
overall[9][7]=0
overall[9][8]=(coeff[7])[0][1]+(coeff[12])[0][2]
overall[9][9]=(coeff[8])[1][1]+(coeff[9])[0][0]+(coeff[14])[0][0]+(coeff[13])[2][2]+(coeff[12])[2][2]+(coeff[7])[1][1]
overall[10][0]=0
overall[10][1]=0
overall[10][2]=0
overall[10][3]=0
overall[10][4]=0
overall[10][5]=0
overall[10][6]=(coeff[9])[1][2]+(coeff[10])[0][1]
overall[10][7]=(coeff[10])[1][2]+(coeff[11])[0][2]
overall[10][8]=0
overall[10][9]=(coeff[9])[0][1]+(coeff[14])[0][2]
overall[10][10]=(coeff[10])[1][1]+(coeff[11])[0][0]+(coeff[16])[0][0]+(coeff[15])[2][2]+(coeff[14])[2][2]+(coeff[9])[1][1]
overall[11][0]=0
overall[11][1]=0
overall[11][2]=0
overall[11][3]=0
overall[11][4]=0
overall[11][5]=0
overall[11][6]=0
overall[11][7]=(coeff[11])[1][2]
overall[11][8]=0
overall[11][9]=0
overall[11][10]=(coeff[11])[0][1]+(coeff[16])[0][2]
overall[11][11]=(coeff[11])[1][1]+(coeff[16])[2][2]+(coeff[17])[2][2]
overall[12][0]=0
overall[12][1]=0
overall[12][2]=0
overall[12][3]=0
overall[12][4]=0
overall[12][5]=0
overall[12][6]=0
overall[12][7]=0
overall[12][8]=(coeff[12])[0][1]
overall[12][9]=(coeff[12])[1][2]+(coeff[13])[0][2]
overall[12][10]=0
overall[12][11]=0
overall[12][12]=(coeff[12])[1][1]+(coeff[13])[0][0]+(coeff[18])[0][0]
overall[13][0]=0
overall[13][1]=0
overall[13][2]=0
overall[13][3]=0
overall[13][4]=0
overall[13][5]=0
overall[13][6]=0
overall[13][7]=0
overall[13][8]=0
overall[13][9]=(coeff[13])[1][2]+(coeff[14])[0][1]
overall[13][10]=(coeff[14])[1][2]+(coeff[15])[0][2]
overall[13][11]=0
overall[13][12]=(coeff[13])[0][1]+(coeff[18])[0][2]
overall[13][13]=(coeff[14])[1][1]+(coeff[15])[0][0]+(coeff[20])[0][0]+(coeff[19])[2][2]+(coeff[18])[2][2]+(coeff[13])[1][1]
overall[14][0]=0
overall[14][1]=0
overall[14][2]=0
overall[14][3]=0
overall[14][4]=0
overall[14][5]=0
overall[14][6]=0
overall[14][7]=0
overall[14][8]=0
overall[14][9]=0
overall[14][10]=(coeff[15])[1][2]+(coeff[16])[0][1]
overall[14][11]=(coeff[16])[1][2]+(coeff[17])[0][2]
overall[14][12]=0
overall[14][13]=(coeff[15])[0][1]+(coeff[20])[0][2]
overall[14][14]=(coeff[16])[1][1]+(coeff[17])[0][0]+(coeff[22])[0][0]+(coeff[21])[2][2]+(coeff[20])[2][2]+(coeff[15])[1][1]
overall[15][0]=0
overall[15][1]=0
overall[15][2]=0
overall[15][3]=0
overall[15][4]=0
overall[15][5]=0
overall[15][6]=0
overall[15][7]=0
overall[15][8]=0
overall[15][9]=0
overall[15][10]=0
overall[15][11]=(coeff[17])[1][2]
overall[15][12]=0
overall[15][13]=0
overall[15][14]=(coeff[17])[0][1]+(coeff[22])[0][2]
overall[15][15]=(coeff[17])[1][1]+(coeff[22])[2][2]+(coeff[23])[2][2]
overall[16][0]=0
overall[16][1]=0
overall[16][2]=0
overall[16][3]=0
overall[16][4]=0
overall[16][5]=0
overall[16][6]=0
overall[16][7]=0
overall[16][8]=0
overall[16][9]=0
overall[16][10]=0
overall[16][11]=0
overall[16][12]=(coeff[18])[0][1]
overall[16][13]=(coeff[18])[1][2]+(coeff[19])[0][2]
overall[16][14]=0
overall[16][15]=0
overall[16][16]=(coeff[18])[1][1]+(coeff[19])[0][0]+(coeff[24])[0][0]
overall[17][0]=0
overall[17][1]=0
overall[17][2]=0
overall[17][3]=0
overall[17][4]=0
overall[17][5]=0
overall[17][6]=0
overall[17][7]=0
overall[17][8]=0
overall[17][9]=0
overall[17][10]=0
overall[17][11]=0
overall[17][12]=0
overall[17][13]=(coeff[19])[1][2]+(coeff[20])[0][1]
overall[17][14]=(coeff[20])[1][2]+(coeff[21])[0][2]
overall[17][15]=0
overall[17][16]=(coeff[19])[0][1]+(coeff[24])[0][2]
overall[17][17]=(coeff[20])[1][1]+(coeff[21])[0][0]+(coeff[26])[0][0]+(coeff[25])[2][2]+(coeff[24])[2][2]+(coeff[19])[1][1]
overall[18][0]=0
overall[18][1]=0
overall[18][2]=0
overall[18][3]=0
overall[18][4]=0
overall[18][5]=0
overall[18][6]=0
overall[18][7]=0
overall[18][8]=0
overall[18][9]=0
overall[18][10]=0
overall[18][11]=0
overall[18][12]=0
overall[18][13]=0
overall[18][14]=(coeff[21])[1][2]+(coeff[22])[0][1]
overall[18][15]=(coeff[22])[1][2]+(coeff[23])[0][2]
overall[18][16]=0
overall[18][17]=(coeff[21])[0][1]+(coeff[26])[0][2]
overall[18][18]=(coeff[22])[1][1]+(coeff[23])[0][0]+(coeff[28])[0][0]+(coeff[27])[2][2]+(coeff[26])[2][2]+(coeff[21])[1][1]
overall[19][0]=0
overall[19][1]=0
overall[19][2]=0
overall[19][3]=0
overall[19][4]=0
overall[19][5]=0
overall[19][6]=0
overall[19][7]=0
overall[19][8]=0
overall[19][9]=0
overall[19][10]=0
overall[19][11]=0
overall[19][12]=0
overall[19][13]=0
overall[19][14]=0
overall[19][15]=(coeff[23])[1][2]
overall[19][16]=0
overall[19][17]=0
overall[19][18]=(coeff[23])[0][1]+(coeff[28])[0][2]
overall[19][19]=(coeff[23])[1][1]+(coeff[28])[2][2]+(coeff[29])[2][2]
overall[20][0]=0
overall[20][1]=0
overall[20][2]=0
overall[20][3]=0
overall[20][4]=0
overall[20][5]=0
overall[20][6]=0
overall[20][7]=0
overall[20][8]=0
overall[20][9]=0
overall[20][10]=0
overall[20][11]=0
overall[20][12]=0
overall[20][13]=0
overall[20][14]=0
overall[20][15]=0
overall[20][16]=(coeff[24])[0][1]
overall[20][17]=(coeff[24])[1][2]+(coeff[25])[0][2]
overall[20][18]=0
overall[20][19]=0
overall[20][20]=(coeff[24])[1][1]+(coeff[25])[0][0]+(coeff[30])[0][0]
overall[21][0]=0
overall[21][1]=0
overall[21][2]=0
overall[21][3]=0
overall[21][4]=0
overall[21][5]=0
overall[21][6]=0
overall[21][7]=0
overall[21][8]=0
overall[21][9]=0
overall[21][10]=0
overall[21][11]=0
overall[21][12]=0
overall[21][13]=0
overall[21][14]=0
overall[21][15]=0
overall[21][16]=0
overall[21][17]=(coeff[25])[1][2]+(coeff[26])[0][1]
overall[21][18]=(coeff[26])[1][2]+(coeff[27])[0][2]
overall[21][19]=0
overall[21][20]=(coeff[25])[0][1]+(coeff[30])[0][2]
overall[21][21]=(coeff[26])[1][1]+(coeff[27])[0][0]+(coeff[32])[0][0]+(coeff[31])[2][2]+(coeff[30])[2][2]+(coeff[25])[1][1]
overall[22][0]=0
overall[22][1]=0
overall[22][2]=0
overall[22][3]=0
overall[22][4]=0
overall[22][5]=0
overall[22][6]=0
overall[22][7]=0
overall[22][8]=0
overall[22][9]=0
overall[22][10]=0
overall[22][11]=0
overall[22][12]=0
overall[22][13]=0
overall[22][14]=0
overall[22][15]=0
overall[22][16]=0
overall[22][17]=0
overall[22][18]=(coeff[27])[1][2]+(coeff[28])[0][1]
overall[22][19]=(coeff[28])[1][2]+(coeff[29])[0][2]
overall[22][20]=0
overall[22][21]=(coeff[27])[0][1]+(coeff[32])[0][2]
overall[22][22]=(coeff[28])[1][1]+(coeff[29])[0][0]+(coeff[34])[0][0]+(coeff[33])[2][2]+(coeff[32])[2][2]+(coeff[27])[1][1]
overall[23][0]=0
overall[23][1]=0
overall[23][2]=0
overall[23][3]=0
overall[23][4]=0
overall[23][5]=0
overall[23][6]=0
overall[23][7]=0
overall[23][8]=0
overall[23][9]=0
overall[23][10]=0
overall[23][11]=0
overall[23][12]=0
overall[23][13]=0
overall[23][14]=0
overall[23][15]=0
overall[23][16]=0
overall[23][17]=0
overall[23][18]=0
overall[23][19]=(coeff[29])[1][2]
overall[23][20]=0
overall[23][21]=0
overall[23][22]=(coeff[29])[0][1]+(coeff[34])[0][2]
overall[23][23]=(coeff[29])[1][1]+(coeff[34])[2][2]+(coeff[35])[2][2]
overall[24][0]=0
overall[24][1]=0
overall[24][2]=0
overall[24][3]=0
overall[24][4]=0
overall[24][5]=0
overall[24][6]=0
overall[24][7]=0
overall[24][8]=0
overall[24][9]=0
overall[24][10]=0
overall[24][11]=0
overall[24][12]=0
overall[24][13]=0
overall[24][14]=0
overall[24][15]=0
overall[24][16]=0
overall[24][17]=0
overall[24][18]=0
overall[24][19]=0
overall[24][20]=(coeff[30])[0][1]
overall[24][21]=(coeff[30])[1][2]+(coeff[31])[0][2]
overall[24][22]=0
overall[24][23]=0
overall[24][24]=(coeff[30])[1][1]+(coeff[31])[0][0]
overall[25][0]=0
overall[25][1]=0
overall[25][2]=0
overall[25][3]=0
overall[25][4]=0
overall[25][5]=0
overall[25][6]=0
overall[25][7]=0
overall[25][8]=0
overall[25][9]=0
overall[25][10]=0
overall[25][11]=0
overall[25][12]=0
overall[25][13]=0
overall[25][14]=0
overall[25][15]=0
overall[25][16]=0
overall[25][17]=0
overall[25][18]=0
overall[25][19]=0
overall[25][20]=0
overall[25][21]=(coeff[31])[1][2]+(coeff[32])[0][1]
overall[25][22]=(coeff[32])[1][2]+(coeff[33])[0][2]
overall[25][23]=0
overall[25][24]=(coeff[31])[0][1]
overall[25][25]=(coeff[31])[1][1]+(coeff[32])[1][1]+(coeff[33])[0][0]
overall[26][0]=0
overall[26][1]=0
overall[26][2]=0
overall[26][3]=0
overall[26][4]=0
overall[26][5]=0
overall[26][6]=0
overall[26][7]=0
overall[26][8]=0
overall[26][9]=0
overall[26][10]=0
overall[26][11]=0
overall[26][12]=0
overall[26][13]=0
overall[26][14]=0
overall[26][15]=0
overall[26][16]=0
overall[26][17]=0
overall[26][18]=0
overall[26][19]=0
overall[26][20]=0
overall[26][21]=0
overall[26][22]=(coeff[33])[1][2]+(coeff[34])[0][1]
overall[26][23]=(coeff[34])[1][2]+(coeff[35])[0][2]
overall[26][24]=0
overall[26][25]=(coeff[33])[0][1]
overall[26][26]=(coeff[33])[1][1]+(coeff[34])[1][1]+(coeff[35])[0][0]
overall[27][0]=0
overall[27][1]=0
overall[27][2]=0
overall[27][3]=0
overall[27][4]=0
overall[27][5]=0
overall[27][6]=0
overall[27][7]=0
overall[27][8]=0
overall[27][9]=0
overall[27][10]=0
overall[27][11]=0
overall[27][12]=0
overall[27][13]=0
overall[27][14]=0
overall[27][15]=0
overall[27][16]=0
overall[27][17]=0
overall[27][18]=0
overall[27][19]=0
overall[27][20]=0
overall[27][21]=0
overall[27][22]=0
overall[27][23]=(coeff[35])[1][2]
overall[27][24]=0
overall[27][25]=0
overall[27][26]=(coeff[35])[0][1]
overall[27][27]=(coeff[35])[1][1]

#print(overall)

Overall/Global Coefficient Matrix:


In [6]:
np.set_printoptions(suppress=True)
for x in range((len(overall))-1):
    for y in range(x+1,len(overall[0])):
        overall[x][y]=overall[y][x]
for x in range(len(overall)):
    for y in range(len(overall[0])):
        overall[x][y]=round(overall[x][y], 10)
print("Overall/Global Coefficient Matrix:")
print(" ")
print(overall)

Overall/Global Coefficient Matrix:
 
[[  9.28625926  -9.25925926   0.           0.          -0.027
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.        ]
 [ -9.25925926  18.57251852  -9.25925926   0.           0.
   -0.054        0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.        ]
 [  0.          -9.25925926  18.57251852  -9.25925926   0.
    0.          -0.054        0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.     

In [7]:
#On differenttiating the energy matrix wrt vf and setting to zero. We get (Cff*vf = −Cfp*vp). 
#From this we find Vf(voltage) at free nodes.
#Cff(free to free node)
#Cff[i][j]=Overall Global Coefficient value of ith free node to jth free node
cff = np.zeros((1,14))
cff = [2, 3, 6, 7, 10, 11, 14, 15, 18, 19, 22, 23, 26, 27]
cff_matrix = np.zeros((len(cff),len(cff)))
for x in range(len(cff)):
    for y in range(len(cff)):
        cff_matrix[x][y]=overall[cff[x]-1][cff[y]-1]
for x in range(len(cff_matrix)):
    for y in range(len(cff_matrix[0])):
        cff_matrix[x][y]=round(cff_matrix[x][y], 10)
print("Cff_Matrix :")
print(" ")
print(cff_matrix)


Cff_Matrix :
 
[[ 18.57251852  -9.25925926  -0.054        0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [ -9.25925926  18.57251852   0.          -0.054        0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [ -0.054        0.          37.14503704 -18.51851852  -0.054
    0.           0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [  0.          -0.054      -18.51851852  37.14503704   0.
   -0.054        0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [  0.           0.          -0.054        0.          37.14503704
  -18.51851852  -0.054        0.           0.           0.
    0.           0.           0.           0.        ]
 [  0.           0.           0.          -0.054      -18.51851852
   37.14503704   0.          -0.054       

In [8]:
inverse_cff = slin.inv(cff_matrix)
print("Inverse Cff Matrix : ")
print(" ")
print(inverse_cff)

Inverse Cff Matrix : 
 
[[0.07165291 0.03572269 0.00017308 0.00013822 0.00000047 0.00000043
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.03572269 0.07165291 0.00013822 0.00017308 0.00000043 0.00000047
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.00017308 0.00013822 0.03582669 0.01786156 0.00008654 0.00006911
  0.00000023 0.00000022 0.         0.         0.         0.
  0.         0.        ]
 [0.00013822 0.00017308 0.01786156 0.03582669 0.00006911 0.00008654
  0.00000022 0.00000023 0.         0.         0.         0.
  0.         0.        ]
 [0.00000047 0.00000043 0.00008654 0.00006911 0.03582646 0.01786135
  0.00008654 0.00006911 0.00000023 0.00000022 0.         0.
  0.         0.        ]
 [0.00000043 0.00000047 0.00006911 0.00008654 0.01786135 0.03582646
  0.00006911 0.00008654 0.00000022 0.00000023 0.         0.
  0.         0.        ]
 [0.         0.         0.00000023 0.00000022 0.00008654 0

In [9]:
#Vp (Voltage of prescribed Nodes)
Vp_matrix = np.zeros((14,1))
for x in range(len(Vp_matrix)):
    if(x%2==0):
        Vp_matrix[x][0]=5
    else:
        Vp_matrix[x][0]=-5
print("Vp Matrix :")
print(" ")
print(Vp_matrix)

Vp Matrix :
 
[[ 5.]
 [-5.]
 [ 5.]
 [-5.]
 [ 5.]
 [-5.]
 [ 5.]
 [-5.]
 [ 5.]
 [-5.]
 [ 5.]
 [-5.]
 [ 5.]
 [-5.]]


In [10]:
#Cfp matrix (Free to prescribed nodes)
cfp_row = cff
cfp_col = [1, 4, 5, 8, 9, 12, 13, 16, 17, 20, 21, 24, 25, 28]
cfp_matrix = np.zeros((len(cfp_row),len(cfp_col)))
for x in range(len(cfp_matrix)):
    for y in range(len(cfp_matrix[0])):
        cfp_matrix[x][y]=overall[cfp_row[x]-1][cfp_col[y]-1]
for x in range(len(cfp_matrix)):
    for y in range(len(cfp_matrix[0])):
        cfp_matrix[x][y]=round(cfp_matrix[x][y], 3)
print("Cfp Matrix :")
print(" ")
print(cfp_matrix)

Cfp Matrix :
 
[[ -9.259   0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.     -9.259   0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.    -18.519   0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.    -18.519   0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.      0.    -18.519   0.      0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.      0.      0.    -18.519   0.      0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.      0.      0.      0.    -18.519   0.      0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.      0.      0.      0.      0.    -18.519   0.
    0.      0.      0.      0.      0.   ]
 [  0.      0.      0.      0.      0.      0.      0.      0.    -18.519

In [11]:
b_matrix = -1*((cfp_matrix).dot(Vp_matrix))
print("B_Matrix :")
print(" ")
print(b_matrix)

B_Matrix :
 
[[ 46.295]
 [-46.295]
 [ 92.595]
 [-92.595]
 [ 92.595]
 [-92.595]
 [ 92.595]
 [-92.595]
 [ 92.595]
 [-92.595]
 [ 92.595]
 [-92.595]
 [ 46.295]
 [-46.295]]


In [12]:
#Vf = voltage at free nodes = (Cff)inverse * (B)
Vf_matrix = (inverse_cff).dot(b_matrix)
print("Voltages at free nodes :")
print(" ")
for x in range(len(Vf_matrix)):
    Vf_matrix[x][0]=round(Vf_matrix[x][0], 3)
    print("Voltage at free node",cff[x],": ",Vf_matrix[x][0])
#print(Vf_matrix)

Voltages at free nodes :
 
Voltage at free node 2 :  1.667
Voltage at free node 3 :  -1.667
Voltage at free node 6 :  1.667
Voltage at free node 7 :  -1.667
Voltage at free node 10 :  1.667
Voltage at free node 11 :  -1.667
Voltage at free node 14 :  1.667
Voltage at free node 15 :  -1.667
Voltage at free node 18 :  1.667
Voltage at free node 19 :  -1.667
Voltage at free node 22 :  1.667
Voltage at free node 23 :  -1.667
Voltage at free node 26 :  1.667
Voltage at free node 27 :  -1.667


In [13]:
electric_field = np.zeros((7,1))
k=0
print("Electric Field in (V/m):")
print(" ")
for x in range(1, len(cff), 2):
    electric_field[k][0]=(Vf_matrix[x-1][0]-Vf_matrix[x][0])/(hor_d*10**-2)
    k+=1
print(electric_field)

Electric Field in (V/m):
 
[[6174.07407407]
 [6174.07407407]
 [6174.07407407]
 [6174.07407407]
 [6174.07407407]
 [6174.07407407]
 [6174.07407407]]


In [14]:
#According to Gauss Law,charge enclosed is equal to net flux crossing the surface area.
#Q(enclosed)=Electric Field * dielectric * ephsilon0 * Area
charge = electric_field[0][0]*5*8.854187817*10**-12*6*10**-4
print("Charge :",charge,"C")

Charge : 1.6399923434376666e-10 C


In [15]:
capacitance = charge/(5-(-5))
capacitance = capacitance*10**12
print("Capacitance :",capacitance,"pF")

Capacitance : 16.399923434376667 pF


In [16]:
analytic_capacitance = 5*8.854187817*10**-12*6*10**-4/(1.62*10**-3)
analytic_capacitance = analytic_capacitance*10**-12
print("Capacitance using Formula :",analytic_capacitance,"pF")

Capacitance using Formula : 1.639664410555555e-23 pF
