In [1]:
import numpy as np
from numpy import *
import scipy.linalg as slin

In [2]:
#declaring the array
np.set_printoptions(suppress=True)
diff_x = (0.162/5)
diff_y = (6/8)
diff_x_sq = diff_x**2
diff_y_sq = diff_y**2
a = np.zeros((28,28))
#print("Matrix A=",a)
#print(type(a))
b = np.zeros((28,1))
#print("Matrix B=",b)
#print(type(b))
for x in range(28):
    if((x%4)==0):
        b[x]=-5*(diff_y_sq)
    elif((x%4)==3):
        b[x]=+5*(diff_y_sq)
#print("Matrix B=",b)
#print(len(a))
#print(len(a[0]))
up = 4
for x in range(len(a)):
    for y in range(len(a[0])):
        if(y==x):
            a[x][y]=-2*(diff_x_sq + diff_y_sq)
        elif((y==(x+1)) and ((y%4)!=0)):
            a[x][y]=diff_y_sq
        elif((x==(y+1)) and ((x%4)!=0)):
            a[x][y]=diff_y_sq
for x in range(len(a)):
    for y in range(len(a[0])):
        if((y==(x+up)) or (x==(y+up))):
            a[x][y]=diff_x_sq
print(a)
print(b)

[[-1.12709952  0.5625      0.          0.          0.00104976  0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.5625     -1.12709952  0.5625      0.          0.          0.00104976
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.5625     -1.12709952  0.5625      0.          0.
   0.00104976  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.5625     -1.127099

In [3]:
print("Determinant of a=",slin.det(a))  #Determinant of the array
print("Trace of a=",np.trace(a))        #Trace of the array
#print("Transpose=",np.transpose(a))#Transpose of the array
#print("Inverse=",slin.inv(a))      #Inverse of the array

Determinant of a= 0.008737374088198873
Trace of a= -31.55878656000001


In [4]:
#print((slin.inv(a)).dot(b))
#print("Length=",len((slin.inv(a)).dot(b)))
c = (slin.inv(a)).dot(b)
for x in range(len(c)):
    print("Calculated Voltage at Free Node ",x+1,"equals ",c[x])

Calculated Voltage at Free Node  1 equals  [2.99627724]
Calculated Voltage at Free Node  2 equals  [0.99813931]
Calculated Voltage at Free Node  3 equals  [-0.99813931]
Calculated Voltage at Free Node  4 equals  [-2.99627724]
Calculated Voltage at Free Node  5 equals  [2.99999515]
Calculated Voltage at Free Node  6 equals  [0.99999723]
Calculated Voltage at Free Node  7 equals  [-0.99999723]
Calculated Voltage at Free Node  8 equals  [-2.99999515]
Calculated Voltage at Free Node  9 equals  [2.99999999]
Calculated Voltage at Free Node  10 equals  [1.]
Calculated Voltage at Free Node  11 equals  [-1.]
Calculated Voltage at Free Node  12 equals  [-2.99999999]
Calculated Voltage at Free Node  13 equals  [3.]
Calculated Voltage at Free Node  14 equals  [1.]
Calculated Voltage at Free Node  15 equals  [-1.]
Calculated Voltage at Free Node  16 equals  [-3.]
Calculated Voltage at Free Node  17 equals  [2.99999999]
Calculated Voltage at Free Node  18 equals  [1.]
Calculated Voltage at Free Node

In [5]:
volt = np.zeros((7,4))
for x in range(len(c)):
    volt[(int)(x/4)][(x%4)]=c[x]
pos_volt = 5*(np.ones((7,1)))
neg_volt = -5*(np.ones((7,1)))
#print(pos_volt,neg_volt)
#print(volt)
new_volt = np.hstack((pos_volt,volt,neg_volt))
print("Voltages at different nodes in solution region:")
print(" ")
print(new_volt)
print(" ")
d = 0.162/500
ele = np.zeros((7,5))
#print(ele)
for x in range(len(ele)):
    for y in range(len(ele[0])):
        ele[x][y] = (new_volt[x][y]-new_volt[x][y+1])/d
print("Electric Field at different region in solution region:")
print(" ")
print(ele)

Voltages at different nodes in solution region:
 
[[ 5.          2.99627724  0.99813931 -0.99813931 -2.99627724 -5.        ]
 [ 5.          2.99999515  0.99999723 -0.99999723 -2.99999515 -5.        ]
 [ 5.          2.99999999  1.         -1.         -2.99999999 -5.        ]
 [ 5.          3.          1.         -1.         -3.         -5.        ]
 [ 5.          2.99999999  1.         -1.         -2.99999999 -5.        ]
 [ 5.          2.99999515  0.99999723 -0.99999723 -2.99999515 -5.        ]
 [ 5.          2.99627724  0.99813931 -0.99813931 -2.99627724 -5.        ]]
 
Electric Field at different region in solution region:
 
[[6184.32950738 6167.09236565 6161.3537848  6167.09236565 6184.32950738]
 [6172.85447566 6172.8330884  6172.82240274 6172.8330884  6172.85447566]
 [6172.83952607 6172.83949821 6172.8394823  6172.83949821 6172.83952607]
 [6172.83950623 6172.83950615 6172.83950611 6172.83950615 6172.83950623]
 [6172.83952607 6172.83949821 6172.8394823  6172.83949821 6172.83952607]


In [6]:
epsilon=8.854187871*10**-12
flux_density = 5*epsilon*ele
print("Flux Density:")
print(" ")
print(flux_density)
ref = np.ones((5,1))
net_flux_density = flux_density.dot(ref)
print(" ")
print("Net Flux Density in one direction:")
print(" ")
print(net_flux_density)

Flux Density:
 
[[0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]
 [0.00000027 0.00000027 0.00000027 0.00000027 0.00000027]]
 
Net Flux Density in one direction:
 
[[0.00000137]
 [0.00000137]
 [0.00000137]
 [0.00000137]
 [0.00000137]
 [0.00000137]
 [0.00000137]]


In [7]:
length_of_plate = 0.06
width_of_plate = 0.01
Area_of_plate = length_of_plate*width_of_plate
Total_flux = net_flux_density[0][0]*Area_of_plate
print("Total Flux through Epoxy dielectic:",Total_flux)

Total Flux through Epoxy dielectic: 8.198322102777778e-10


In [8]:
#From Gauss Law net flux passing through an area is equal to the charge enclosed within the gaussian surface
charge = Total_flux
Capacitance = charge/5
print("Capacitance is equal to =",Capacitance)

Capacitance is equal to = 1.6396644205555555e-10
